export const CATEGORIES = [
  "All",
  "CRM & Sales",
  "Communication",
  "Payments",
  "Marketing & Email",
  "Analytics",
  "Project Management",
  "Databases",
  "Automation",
  "Developer Tools",
  "E-commerce",
  "File Storage",
  "Scheduling",
  "AI & ML",
  "Customer Support",
  "HR & Operations",
  "Social Media",
  "Finance & Accounting",
] as const;

export type IntegrationCategory = (typeof CATEGORIES)[number];

/**
 * A single credential field. Most integrations capture one value (the API key),
 * but some providers need several (e.g. Twilio = SID + token + from-number). Each
 * field is stored under its own `key` in user_integrations so the run-workflow
 * engine can resolve them independently as operator BYO credentials.
 */
export interface IntegrationField {
  key: string;
  label: string;
  hint: string;
  inputType: "key" | "url" | "text";
  optional?: boolean;
}

export interface IntegrationDef {
  key: string;
  name: string;
  category: IntegrationCategory;
  description: string;
  iconSlug?: string; // Simple Icons CDN slug
  inputType: "key" | "url" | "bearer" | "oauth";
  hint: string;
  popular?: boolean;
  comingSoon?: boolean;
  // When present, the Connect modal captures these fields instead of a single value.
  fields?: IntegrationField[];
}

export const CATALOG: IntegrationDef[] = [
  // ── CRM & Sales ──────────────────────────────────────────
  {
    key: "hubspot",
    name: "HubSpot",
    category: "CRM & Sales",
    description: "All-in-one CRM, marketing, sales, and service platform.",
    iconSlug: "hubspot",
    inputType: "key",
    hint: "Private app access token",
    popular: true,
  },
  {
    key: "gohighlevel",
    name: "GoHighLevel",
    category: "CRM & Sales",
    description: "All-in-one sales and marketing CRM for agencies.",
    iconSlug: "gohighlevel",
    inputType: "key",
    hint: "API key",
    popular: true,
  },
  {
    key: "salesforce",
    name: "Salesforce",
    category: "CRM & Sales",
    description: "The world's #1 CRM platform.",
    iconSlug: "salesforce",
    inputType: "key",
    hint: "OAuth coming soon",
    comingSoon: true,
    popular: true,
  },
  {
    key: "pipedrive",
    name: "Pipedrive",
    category: "CRM & Sales",
    description: "Visual sales CRM and pipeline management tool.",
    iconSlug: "pipedrive",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "zoho_crm",
    name: "Zoho CRM",
    category: "CRM & Sales",
    description: "Comprehensive CRM for businesses of all sizes.",
    iconSlug: "zoho",
    inputType: "key",
    hint: "Client secret",
  },
  {
    key: "activecamp",
    name: "ActiveCampaign",
    category: "CRM & Sales",
    description: "Customer experience automation and CRM.",
    iconSlug: "activecampaign",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "monday_crm",
    name: "Monday CRM",
    category: "CRM & Sales",
    description: "Visual CRM built on Work OS.",
    iconSlug: "monday",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "keap",
    name: "Keap",
    category: "CRM & Sales",
    description: "CRM and marketing automation for small businesses.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "copper",
    name: "Copper",
    category: "CRM & Sales",
    description: "CRM built natively for Google Workspace.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "close_io",
    name: "Close",
    category: "CRM & Sales",
    description: "CRM designed for inside sales teams.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "insightly",
    name: "Insightly",
    category: "CRM & Sales",
    description: "CRM and project management platform.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "nutshell",
    name: "Nutshell",
    category: "CRM & Sales",
    description: "Simple, powerful CRM for B2B sales.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "freshsales",
    name: "Freshsales",
    category: "CRM & Sales",
    description: "AI-powered CRM by Freshworks.",
    iconSlug: "freshworks",
    inputType: "key",
    hint: "API key",
  },

  // ── Communication ────────────────────────────────────────
  {
    key: "slack",
    name: "Slack",
    category: "Communication",
    description: "Team messaging, channels, and collaboration.",
    iconSlug: "slack",
    inputType: "url",
    hint: "https://hooks.slack.com/services/...",
    popular: true,
  },
  {
    key: "discord",
    name: "Discord",
    category: "Communication",
    description: "Community and team voice, video, and text chat.",
    iconSlug: "discord",
    inputType: "url",
    hint: "https://discord.com/api/webhooks/...",
  },
  {
    key: "msteams",
    name: "Microsoft Teams",
    category: "Communication",
    description: "Enterprise messaging, meetings, and collaboration.",
    iconSlug: "microsoftteams",
    inputType: "url",
    hint: "Incoming webhook URL",
  },
  {
    key: "telegram",
    name: "Telegram",
    category: "Communication",
    description: "Messaging platform with powerful bot automation.",
    iconSlug: "telegram",
    inputType: "key",
    hint: "Bot token",
  },
  {
    key: "twilio",
    name: "Twilio",
    category: "Communication",
    description: "SMS, voice, email, and messaging APIs.",
    iconSlug: "twilio",
    inputType: "key",
    hint: "Auth token",
    fields: [
      { key: "twilio_sid", label: "Account SID", hint: "AC…", inputType: "key" },
      { key: "twilio", label: "Auth token", hint: "Your Twilio auth token", inputType: "key" },
      { key: "twilio_from", label: "From number", hint: "+15551234567", inputType: "text" },
    ],
  },
  {
    key: "sendgrid",
    name: "SendGrid",
    category: "Communication",
    description: "Reliable transactional email delivery.",
    iconSlug: "sendgrid",
    inputType: "key",
    hint: "API key (SG...)",
    popular: true,
    fields: [
      { key: "sendgrid", label: "API key", hint: "API key (SG…)", inputType: "key" },
      {
        key: "sendgrid_from",
        label: "From email (verified sender)",
        hint: "you@yourdomain.com",
        inputType: "text",
      },
    ],
  },
  {
    key: "mailchimp",
    name: "Mailchimp",
    category: "Communication",
    description: "Email marketing, automation, and audiences.",
    iconSlug: "mailchimp",
    inputType: "key",
    hint: "API key",
    popular: true,
  },
  {
    key: "klaviyo",
    name: "Klaviyo",
    category: "Communication",
    description: "Email and SMS marketing for e-commerce.",
    iconSlug: "klaviyo",
    inputType: "key",
    hint: "Private API key",
  },
  {
    key: "intercom",
    name: "Intercom",
    category: "Communication",
    description: "Customer messaging, live chat, and support.",
    iconSlug: "intercom",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "brevo",
    name: "Brevo",
    category: "Communication",
    description: "Email, SMS, and chat marketing platform.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "postmark",
    name: "Postmark",
    category: "Communication",
    description: "Fast, reliable transactional email delivery.",
    inputType: "key",
    hint: "Server API token",
  },
  {
    key: "resend",
    name: "Resend",
    category: "Communication",
    description: "Modern email API built for developers.",
    inputType: "key",
    hint: "API key (re_...)",
  },
  {
    key: "vonage",
    name: "Vonage",
    category: "Communication",
    description: "Communications APIs for SMS, voice, and video.",
    inputType: "key",
    hint: "API secret",
  },

  // ── Payments ─────────────────────────────────────────────
  {
    key: "stripe",
    name: "Stripe",
    category: "Payments",
    description: "Online payment processing for internet businesses.",
    iconSlug: "stripe",
    inputType: "key",
    hint: "sk_live_... or sk_test_...",
    popular: true,
  },
  {
    key: "paypal",
    name: "PayPal",
    category: "Payments",
    description: "Global digital payments and commerce.",
    iconSlug: "paypal",
    inputType: "key",
    hint: "Client secret",
    popular: true,
  },
  {
    key: "square",
    name: "Square",
    category: "Payments",
    description: "Payment processing and business management.",
    iconSlug: "square",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "braintree",
    name: "Braintree",
    category: "Payments",
    description: "PayPal's full-stack payment gateway.",
    iconSlug: "braintree",
    inputType: "key",
    hint: "Private key",
  },
  {
    key: "plaid",
    name: "Plaid",
    category: "Payments",
    description: "Connect bank accounts and verify finances.",
    iconSlug: "plaid",
    inputType: "key",
    hint: "Secret key",
  },
  {
    key: "mollie",
    name: "Mollie",
    category: "Payments",
    description: "European payment service provider.",
    iconSlug: "mollie",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "paddle",
    name: "Paddle",
    category: "Payments",
    description: "Revenue delivery platform for software companies.",
    iconSlug: "paddle",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "lemonsqueezy",
    name: "Lemon Squeezy",
    category: "Payments",
    description: "Payments and subscriptions for indie developers.",
    iconSlug: "lemonsqueezy",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "adyen",
    name: "Adyen",
    category: "Payments",
    description: "Global end-to-end payments platform.",
    iconSlug: "adyen",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "coinbase_commerce",
    name: "Coinbase Commerce",
    category: "Payments",
    description: "Accept cryptocurrency payments.",
    iconSlug: "coinbase",
    inputType: "key",
    hint: "API key",
  },

  // ── Marketing & Email ─────────────────────────────────────
  {
    key: "convertkit",
    name: "ConvertKit",
    category: "Marketing & Email",
    description: "Email marketing platform built for creators.",
    iconSlug: "convertkit",
    inputType: "key",
    hint: "API secret",
  },
  {
    key: "mailerlite",
    name: "MailerLite",
    category: "Marketing & Email",
    description: "Simple, powerful email marketing platform.",
    iconSlug: "mailerlite",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "beehiiv",
    name: "Beehiiv",
    category: "Marketing & Email",
    description: "Newsletter platform built for growth.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "drip",
    name: "Drip",
    category: "Marketing & Email",
    description: "E-commerce email automation CRM.",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "constantcontact",
    name: "Constant Contact",
    category: "Marketing & Email",
    description: "Email and digital marketing tools.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "omnisend",
    name: "Omnisend",
    category: "Marketing & Email",
    description: "Omnichannel marketing automation for e-commerce.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "campaignmonitor",
    name: "Campaign Monitor",
    category: "Marketing & Email",
    description: "Beautiful email marketing platform.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "aweber",
    name: "AWeber",
    category: "Marketing & Email",
    description: "Email marketing and automation tools.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "getresponse",
    name: "GetResponse",
    category: "Marketing & Email",
    description: "Online marketing and automation platform.",
    inputType: "key",
    hint: "API key",
  },

  // ── Analytics ─────────────────────────────────────────────
  {
    key: "googleanalytics",
    name: "Google Analytics",
    category: "Analytics",
    description: "Website traffic, behavior, and conversion analytics.",
    iconSlug: "googleanalytics",
    inputType: "key",
    hint: "Measurement ID / API secret",
    popular: true,
  },
  {
    key: "mixpanel",
    name: "Mixpanel",
    category: "Analytics",
    description: "Product analytics, funnels, and retention.",
    iconSlug: "mixpanel",
    inputType: "key",
    hint: "Project token",
  },
  {
    key: "amplitude",
    name: "Amplitude",
    category: "Analytics",
    description: "Digital analytics platform for product teams.",
    iconSlug: "amplitude",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "segment",
    name: "Segment",
    category: "Analytics",
    description: "Customer data platform and event routing.",
    iconSlug: "segment",
    inputType: "key",
    hint: "Write key",
  },
  {
    key: "hotjar",
    name: "Hotjar",
    category: "Analytics",
    description: "Heatmaps, session recordings, and surveys.",
    iconSlug: "hotjar",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "posthog",
    name: "PostHog",
    category: "Analytics",
    description: "Open-source product analytics suite.",
    iconSlug: "posthog",
    inputType: "key",
    hint: "Project API key",
  },
  {
    key: "plausible",
    name: "Plausible",
    category: "Analytics",
    description: "Privacy-first, lightweight web analytics.",
    iconSlug: "plausible",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "fullstory",
    name: "FullStory",
    category: "Analytics",
    description: "Digital experience analytics and session replay.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "logrocket",
    name: "LogRocket",
    category: "Analytics",
    description: "Frontend performance monitoring and session replay.",
    iconSlug: "logrocket",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "clarity",
    name: "Microsoft Clarity",
    category: "Analytics",
    description: "Free heatmaps and session recordings.",
    iconSlug: "microsoftclarity",
    inputType: "key",
    hint: "Project ID",
  },

  // ── Project Management ────────────────────────────────────
  {
    key: "notion",
    name: "Notion",
    category: "Project Management",
    description: "All-in-one workspace with docs, wikis, and databases.",
    iconSlug: "notion",
    inputType: "key",
    hint: "Integration token",
    popular: true,
  },
  {
    key: "asana",
    name: "Asana",
    category: "Project Management",
    description: "Team task and work management platform.",
    iconSlug: "asana",
    inputType: "key",
    hint: "Personal access token",
    popular: true,
  },
  {
    key: "trello",
    name: "Trello",
    category: "Project Management",
    description: "Visual kanban boards for project management.",
    iconSlug: "trello",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "linear",
    name: "Linear",
    category: "Project Management",
    description: "Modern issue tracking for software teams.",
    iconSlug: "linear",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "jira",
    name: "Jira",
    category: "Project Management",
    description: "Agile project and issue tracking by Atlassian.",
    iconSlug: "jira",
    inputType: "key",
    hint: "API token",
    popular: true,
  },
  {
    key: "clickup",
    name: "ClickUp",
    category: "Project Management",
    description: "All-in-one productivity and project management.",
    iconSlug: "clickup",
    inputType: "key",
    hint: "Personal API token",
  },
  {
    key: "basecamp",
    name: "Basecamp",
    category: "Project Management",
    description: "Project management and team communication.",
    iconSlug: "basecamp",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "todoist",
    name: "Todoist",
    category: "Project Management",
    description: "Task manager for individuals and teams.",
    iconSlug: "todoist",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "wrike",
    name: "Wrike",
    category: "Project Management",
    description: "Collaborative work and project management.",
    iconSlug: "wrike",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "confluence",
    name: "Confluence",
    category: "Project Management",
    description: "Team wiki and knowledge base by Atlassian.",
    iconSlug: "confluence",
    inputType: "key",
    hint: "API token",
  },

  // ── Databases ─────────────────────────────────────────────
  {
    key: "airtable",
    name: "Airtable",
    category: "Databases",
    description: "Flexible database-spreadsheet hybrid for teams.",
    iconSlug: "airtable",
    inputType: "key",
    hint: "Personal access token (pat...)",
    popular: true,
  },
  {
    key: "googlesheets",
    name: "Google Sheets",
    category: "Databases",
    description: "Cloud-based collaborative spreadsheets.",
    iconSlug: "googlesheets",
    inputType: "oauth",
    hint: "OAuth coming soon",
    comingSoon: true,
  },
  {
    key: "firebase",
    name: "Firebase",
    category: "Databases",
    description: "Google's real-time app database and auth.",
    iconSlug: "firebase",
    inputType: "key",
    hint: "Service account JSON",
  },
  {
    key: "mongodb",
    name: "MongoDB",
    category: "Databases",
    description: "Document-oriented NoSQL database.",
    iconSlug: "mongodb",
    inputType: "url",
    hint: "mongodb+srv://...",
  },
  {
    key: "planetscale",
    name: "PlanetScale",
    category: "Databases",
    description: "Serverless MySQL with branching.",
    iconSlug: "planetscale",
    inputType: "key",
    hint: "Service token",
  },
  {
    key: "neon_db",
    name: "Neon",
    category: "Databases",
    description: "Serverless, auto-scaling Postgres.",
    inputType: "url",
    hint: "PostgreSQL connection string",
  },
  {
    key: "redis_io",
    name: "Redis",
    category: "Databases",
    description: "In-memory data structures for caching and queues.",
    iconSlug: "redis",
    inputType: "url",
    hint: "redis://...",
  },
  {
    key: "pinecone",
    name: "Pinecone",
    category: "Databases",
    description: "Vector database for AI and similarity search.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "elastic",
    name: "Elasticsearch",
    category: "Databases",
    description: "Search and analytics engine.",
    iconSlug: "elasticsearch",
    inputType: "url",
    hint: "Cloud endpoint URL",
  },

  // ── Automation ────────────────────────────────────────────
  {
    key: "zapier",
    name: "Zapier",
    category: "Automation",
    description: "Workflow automation across 5,000+ apps.",
    iconSlug: "zapier",
    inputType: "url",
    hint: "https://hooks.zapier.com/hooks/catch/...",
    popular: true,
  },
  {
    key: "make",
    name: "Make",
    category: "Automation",
    description: "Visual no-code automation platform.",
    iconSlug: "make",
    inputType: "url",
    hint: "Webhook URL",
  },
  {
    key: "n8n",
    name: "n8n",
    category: "Automation",
    description: "Open-source workflow automation tool.",
    iconSlug: "n8n",
    inputType: "url",
    hint: "Webhook URL",
  },
  {
    key: "ifttt",
    name: "IFTTT",
    category: "Automation",
    description: "Simple automation for apps and smart devices.",
    iconSlug: "ifttt",
    inputType: "key",
    hint: "Webhook key",
  },
  {
    key: "pipedream",
    name: "Pipedream",
    category: "Automation",
    description: "Integration platform for developers.",
    iconSlug: "pipedream",
    inputType: "url",
    hint: "Webhook URL",
  },
  {
    key: "workato",
    name: "Workato",
    category: "Automation",
    description: "Enterprise integration and process automation.",
    inputType: "url",
    hint: "Webhook URL",
  },

  // ── Developer Tools ───────────────────────────────────────
  {
    key: "github",
    name: "GitHub",
    category: "Developer Tools",
    description: "Code hosting, collaboration, and CI/CD.",
    iconSlug: "github",
    inputType: "key",
    hint: "Personal access token",
    popular: true,
  },
  {
    key: "gitlab",
    name: "GitLab",
    category: "Developer Tools",
    description: "DevOps platform for source code and CI/CD.",
    iconSlug: "gitlab",
    inputType: "key",
    hint: "Personal access token",
  },
  {
    key: "bitbucket",
    name: "Bitbucket",
    category: "Developer Tools",
    description: "Git code hosting by Atlassian.",
    iconSlug: "bitbucket",
    inputType: "key",
    hint: "App password",
  },
  {
    key: "sentry",
    name: "Sentry",
    category: "Developer Tools",
    description: "Error tracking and performance monitoring.",
    iconSlug: "sentry",
    inputType: "key",
    hint: "Auth token",
  },
  {
    key: "datadog",
    name: "Datadog",
    category: "Developer Tools",
    description: "Cloud monitoring, logs, and security.",
    iconSlug: "datadog",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "pagerduty",
    name: "PagerDuty",
    category: "Developer Tools",
    description: "Incident management and on-call alerting.",
    iconSlug: "pagerduty",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "netlify",
    name: "Netlify",
    category: "Developer Tools",
    description: "Web hosting and automated deployments.",
    iconSlug: "netlify",
    inputType: "key",
    hint: "Personal access token",
  },
  {
    key: "vercel_ext",
    name: "Vercel",
    category: "Developer Tools",
    description: "Frontend cloud platform with zero-config deployments.",
    iconSlug: "vercel",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "heroku",
    name: "Heroku",
    category: "Developer Tools",
    description: "Cloud application platform.",
    iconSlug: "heroku",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "circleci",
    name: "CircleCI",
    category: "Developer Tools",
    description: "Continuous integration and delivery platform.",
    iconSlug: "circleci",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "newrelic",
    name: "New Relic",
    category: "Developer Tools",
    description: "Observability and performance monitoring.",
    iconSlug: "newrelic",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "cloudflare_ext",
    name: "Cloudflare",
    category: "Developer Tools",
    description: "CDN, DNS, DDoS protection, and Workers.",
    iconSlug: "cloudflare",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "aws_ext",
    name: "AWS",
    category: "Developer Tools",
    description: "Amazon cloud infrastructure and services.",
    iconSlug: "amazonaws",
    inputType: "key",
    hint: "Secret access key",
  },
  {
    key: "gcp",
    name: "Google Cloud",
    category: "Developer Tools",
    description: "Google cloud computing services.",
    iconSlug: "googlecloud",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "digitalocean",
    name: "DigitalOcean",
    category: "Developer Tools",
    description: "Developer-friendly cloud infrastructure.",
    iconSlug: "digitalocean",
    inputType: "key",
    hint: "Personal access token",
  },

  // ── E-commerce ────────────────────────────────────────────
  {
    key: "shopify",
    name: "Shopify",
    category: "E-commerce",
    description: "Complete e-commerce platform for all business sizes.",
    iconSlug: "shopify",
    inputType: "key",
    hint: "Admin API access token",
    popular: true,
  },
  {
    key: "woocommerce",
    name: "WooCommerce",
    category: "E-commerce",
    description: "WordPress e-commerce plugin with full control.",
    iconSlug: "woocommerce",
    inputType: "key",
    hint: "Consumer secret",
  },
  {
    key: "bigcommerce",
    name: "BigCommerce",
    category: "E-commerce",
    description: "Enterprise-grade SaaS e-commerce.",
    iconSlug: "bigcommerce",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "magento",
    name: "Magento / Adobe Commerce",
    category: "E-commerce",
    description: "Open-source e-commerce for enterprises.",
    iconSlug: "magento",
    inputType: "key",
    hint: "Integration access token",
  },
  {
    key: "wix_stores",
    name: "Wix",
    category: "E-commerce",
    description: "Website builder with built-in e-commerce.",
    iconSlug: "wix",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "squarespace_com",
    name: "Squarespace",
    category: "E-commerce",
    description: "Website builder and online store platform.",
    iconSlug: "squarespace",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "webflow",
    name: "Webflow",
    category: "E-commerce",
    description: "No-code web design, CMS, and e-commerce.",
    iconSlug: "webflow",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "gumroad",
    name: "Gumroad",
    category: "E-commerce",
    description: "Sell digital products and memberships directly.",
    iconSlug: "gumroad",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "recharge",
    name: "Recharge",
    category: "E-commerce",
    description: "Subscription billing and management for Shopify.",
    inputType: "key",
    hint: "API key",
  },

  // ── File Storage ──────────────────────────────────────────
  {
    key: "googledrive",
    name: "Google Drive",
    category: "File Storage",
    description: "Cloud file storage, sync, and collaboration.",
    iconSlug: "googledrive",
    inputType: "oauth",
    hint: "OAuth coming soon",
    comingSoon: true,
  },
  {
    key: "dropbox",
    name: "Dropbox",
    category: "File Storage",
    description: "Cloud storage and intelligent file collaboration.",
    iconSlug: "dropbox",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "onedrive",
    name: "OneDrive",
    category: "File Storage",
    description: "Microsoft personal and business cloud storage.",
    iconSlug: "microsoftonedrive",
    inputType: "oauth",
    hint: "OAuth coming soon",
    comingSoon: true,
  },
  {
    key: "box_io",
    name: "Box",
    category: "File Storage",
    description: "Secure content management and collaboration.",
    iconSlug: "box",
    inputType: "key",
    hint: "Developer token",
  },
  {
    key: "s3",
    name: "Amazon S3",
    category: "File Storage",
    description: "Industry-leading scalable object storage.",
    iconSlug: "amazons3",
    inputType: "key",
    hint: "Secret access key",
  },
  {
    key: "cloudinary",
    name: "Cloudinary",
    category: "File Storage",
    description: "Cloud media management for images and video.",
    iconSlug: "cloudinary",
    inputType: "key",
    hint: "API secret",
  },

  // ── Scheduling ────────────────────────────────────────────
  {
    key: "calendly",
    name: "Calendly",
    category: "Scheduling",
    description: "Automated meeting scheduling and calendar management.",
    iconSlug: "calendly",
    inputType: "key",
    hint: "API token",
    popular: true,
  },
  {
    key: "google_calendar",
    name: "Google Calendar",
    category: "Scheduling",
    description: "Google's calendar and scheduling service.",
    iconSlug: "googlecalendar",
    inputType: "oauth",
    hint: "OAuth coming soon",
    comingSoon: true,
  },
  {
    key: "calcom",
    name: "Cal.com",
    category: "Scheduling",
    description: "Open-source Calendly alternative.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "acuity",
    name: "Acuity Scheduling",
    category: "Scheduling",
    description: "Online appointment scheduling and booking.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "outlook_cal",
    name: "Outlook Calendar",
    category: "Scheduling",
    description: "Microsoft Outlook calendar and scheduling.",
    iconSlug: "microsoftoutlook",
    inputType: "oauth",
    hint: "OAuth coming soon",
    comingSoon: true,
  },

  // ── AI & ML ───────────────────────────────────────────────
  {
    key: "openai",
    name: "OpenAI",
    category: "AI & ML",
    description: "GPT-4, DALL-E, Whisper, and Embeddings APIs.",
    iconSlug: "openai",
    inputType: "key",
    hint: "API key (sk-...)",
    popular: true,
  },
  {
    key: "anthropic",
    name: "Anthropic (Claude)",
    category: "AI & ML",
    description: "Claude AI assistant APIs for text and analysis.",
    iconSlug: "anthropic",
    inputType: "key",
    hint: "API key (sk-ant-...)",
    popular: true,
  },
  {
    key: "huggingface",
    name: "Hugging Face",
    category: "AI & ML",
    description: "Open-source AI models and inference endpoints.",
    iconSlug: "huggingface",
    inputType: "key",
    hint: "Access token (hf_...)",
  },
  {
    key: "cohere",
    name: "Cohere",
    category: "AI & ML",
    description: "Enterprise NLP and text AI models.",
    iconSlug: "cohere",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "replicate",
    name: "Replicate",
    category: "AI & ML",
    description: "Run open-source AI models via API.",
    iconSlug: "replicate",
    inputType: "key",
    hint: "API token (r8_...)",
  },
  {
    key: "groq",
    name: "Groq",
    category: "AI & ML",
    description: "Ultra-fast LLM inference API.",
    inputType: "key",
    hint: "API key (gsk_...)",
  },
  {
    key: "mistral",
    name: "Mistral AI",
    category: "AI & ML",
    description: "Efficient open-weight AI models.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "perplexity",
    name: "Perplexity",
    category: "AI & ML",
    description: "AI-powered search and research answers.",
    iconSlug: "perplexity",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "stability",
    name: "Stability AI",
    category: "AI & ML",
    description: "Stable Diffusion image generation APIs.",
    iconSlug: "stability",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "elevenlabs",
    name: "ElevenLabs",
    category: "AI & ML",
    description: "AI voice synthesis and voice cloning.",
    iconSlug: "elevenlabs",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "deepgram",
    name: "Deepgram",
    category: "AI & ML",
    description: "Fast, accurate speech recognition API.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "assemblyai",
    name: "AssemblyAI",
    category: "AI & ML",
    description: "Speech-to-text and audio AI models.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "langsmith",
    name: "LangSmith",
    category: "AI & ML",
    description: "LangChain observability and tracing platform.",
    inputType: "key",
    hint: "API key",
  },

  // ── Customer Support ──────────────────────────────────────
  {
    key: "zendesk",
    name: "Zendesk",
    category: "Customer Support",
    description: "Customer service platform and support ticketing.",
    iconSlug: "zendesk",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "freshdesk",
    name: "Freshdesk",
    category: "Customer Support",
    description: "Cloud-based helpdesk and customer support.",
    iconSlug: "freshworks",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "helpscout",
    name: "Help Scout",
    category: "Customer Support",
    description: "Customer-focused support platform.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "crisp_io",
    name: "Crisp",
    category: "Customer Support",
    description: "All-in-one customer messaging platform.",
    iconSlug: "crisp",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "front_app",
    name: "Front",
    category: "Customer Support",
    description: "Shared inbox for teams with CRM capabilities.",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "drift",
    name: "Drift",
    category: "Customer Support",
    description: "Conversational marketing and sales platform.",
    iconSlug: "drift",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "tidio",
    name: "Tidio",
    category: "Customer Support",
    description: "Live chat and AI chatbot platform.",
    iconSlug: "tidio",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "gorgias",
    name: "Gorgias",
    category: "Customer Support",
    description: "Helpdesk built specifically for e-commerce.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "kustomer",
    name: "Kustomer",
    category: "Customer Support",
    description: "AI-powered CRM for customer service.",
    inputType: "key",
    hint: "API key",
  },

  // ── HR & Operations ───────────────────────────────────────
  {
    key: "bamboohr",
    name: "BambooHR",
    category: "HR & Operations",
    description: "HR software for growing businesses.",
    iconSlug: "bamboo",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "gusto",
    name: "Gusto",
    category: "HR & Operations",
    description: "Payroll, benefits, and HR platform.",
    iconSlug: "gusto",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "workday",
    name: "Workday",
    category: "HR & Operations",
    description: "Enterprise HR and financial management.",
    iconSlug: "workday",
    inputType: "key",
    hint: "API key",
    comingSoon: true,
  },
  {
    key: "greenhouse",
    name: "Greenhouse",
    category: "HR & Operations",
    description: "Recruiting and onboarding software.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "lever",
    name: "Lever",
    category: "HR & Operations",
    description: "Modern talent acquisition suite.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "rippling",
    name: "Rippling",
    category: "HR & Operations",
    description: "HR, IT, and finance management platform.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "hibob",
    name: "HiBob",
    category: "HR & Operations",
    description: "Modern HR platform for mid-sized companies.",
    inputType: "key",
    hint: "Service user token",
  },
  {
    key: "personio",
    name: "Personio",
    category: "HR & Operations",
    description: "HR software for European SMBs.",
    inputType: "key",
    hint: "API key",
  },

  // ── Social Media ──────────────────────────────────────────
  {
    key: "twitter_x",
    name: "X (Twitter)",
    category: "Social Media",
    description: "Social media platform and news network.",
    iconSlug: "x",
    inputType: "key",
    hint: "Bearer token",
  },
  {
    key: "linkedin_api",
    name: "LinkedIn",
    category: "Social Media",
    description: "Professional networking and B2B advertising.",
    iconSlug: "linkedin",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "facebook_api",
    name: "Facebook",
    category: "Social Media",
    description: "Social network, pages, and ad platform.",
    iconSlug: "facebook",
    inputType: "key",
    hint: "Page access token",
  },
  {
    key: "instagram_api",
    name: "Instagram",
    category: "Social Media",
    description: "Photo and video sharing platform.",
    iconSlug: "instagram",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "tiktok_api",
    name: "TikTok",
    category: "Social Media",
    description: "Short-form video creation and sharing.",
    iconSlug: "tiktok",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "youtube_api",
    name: "YouTube",
    category: "Social Media",
    description: "Video hosting, streaming, and analytics.",
    iconSlug: "youtube",
    inputType: "oauth",
    hint: "OAuth coming soon",
    comingSoon: true,
  },
  {
    key: "reddit_api",
    name: "Reddit",
    category: "Social Media",
    description: "Community-driven content and discussions.",
    iconSlug: "reddit",
    inputType: "key",
    hint: "App secret",
  },
  {
    key: "pinterest_api",
    name: "Pinterest",
    category: "Social Media",
    description: "Visual discovery and image sharing platform.",
    iconSlug: "pinterest",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "buffer",
    name: "Buffer",
    category: "Social Media",
    description: "Social media scheduling and analytics.",
    iconSlug: "buffer",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "hootsuite",
    name: "Hootsuite",
    category: "Social Media",
    description: "Social media management and scheduling.",
    inputType: "key",
    hint: "API key",
  },

  // ── Finance & Accounting ──────────────────────────────────
  {
    key: "quickbooks",
    name: "QuickBooks",
    category: "Finance & Accounting",
    description: "Small business accounting and financial management.",
    iconSlug: "quickbooks",
    inputType: "key",
    hint: "Access token",
  },
  {
    key: "xero",
    name: "Xero",
    category: "Finance & Accounting",
    description: "Cloud accounting for small and medium businesses.",
    iconSlug: "xero",
    inputType: "oauth",
    hint: "OAuth coming soon",
    comingSoon: true,
  },
  {
    key: "freshbooks",
    name: "FreshBooks",
    category: "Finance & Accounting",
    description: "Cloud accounting and invoicing for small businesses.",
    inputType: "key",
    hint: "API token",
  },
  {
    key: "chargebee",
    name: "Chargebee",
    category: "Finance & Accounting",
    description: "Subscription billing and revenue management.",
    iconSlug: "chargebee",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "recurly",
    name: "Recurly",
    category: "Finance & Accounting",
    description: "Subscription management and recurring billing.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "expensify",
    name: "Expensify",
    category: "Finance & Accounting",
    description: "Expense management and reporting.",
    inputType: "key",
    hint: "API key",
  },
  {
    key: "bill_com",
    name: "Bill.com",
    category: "Finance & Accounting",
    description: "Automated accounts payable and receivable.",
    inputType: "key",
    hint: "API key",
  },
];

export const POPULAR_INTEGRATIONS = CATALOG.filter((i) => i.popular);

export function getCatalogByKey(key: string): IntegrationDef | undefined {
  return CATALOG.find((i) => i.key === key);
}

export function searchCatalog(query: string, category: IntegrationCategory): IntegrationDef[] {
  const q = query.toLowerCase().trim();
  return CATALOG.filter((item) => {
    const matchesCat = category === "All" || item.category === category;
    if (!q) return matchesCat;
    const matchesQuery =
      item.name.toLowerCase().includes(q) ||
      item.description.toLowerCase().includes(q) ||
      item.category.toLowerCase().includes(q) ||
      item.key.toLowerCase().includes(q);
    return matchesCat && matchesQuery;
  });
}
