// Closed-loop UI language — the system shows cause-and-effect, never
// backend architecture. One chip vocabulary used across both products so
// "the system is paying attention" reads the same everywhere:
//   action → saved to memory → system update → recommendation → unlocked.

import { Brain, Sparkles, Unlock, RefreshCw, Radar, type LucideIcon } from "lucide-react";

export type ClosedLoopKind = "memory" | "generated" | "unlocked" | "updated" | "learned";

const KINDS: Record<ClosedLoopKind, { label: string; icon: LucideIcon }> = {
  memory: { label: "Saved to memory", icon: Brain },
  generated: { label: "Generated by Bylda", icon: Sparkles },
  unlocked: { label: "Next unlocked", icon: Unlock },
  updated: { label: "Updated from your last action", icon: RefreshCw },
  learned: { label: "Based on what Bylda learned", icon: Radar },
};

export function ClosedLoopChip({
  kind,
  label,
}: {
  kind: ClosedLoopKind;
  /** Override the default copy while keeping the vocabulary's look */
  label?: string;
}) {
  const def = KINDS[kind];
  const Icon = def.icon;
  return (
    <span
      className="inline-flex items-center gap-1 rounded-full border px-2 py-0.5 text-[10px] font-semibold"
      style={{
        color: "var(--primary)",
        background: "var(--primary-soft)",
        borderColor: "var(--primary-border)",
      }}
    >
      <Icon className="h-2.5 w-2.5" />
      {label ?? def.label}
    </span>
  );
}
