-- Migration: create ai_operator_config table
-- Run on Supabase project: ipidfqwlszuhjgjygbvx
-- Referenced by workflows:
--   bylda_ops_ai_profile_builder, bylda_ops_niche_tool_preconfig,
--   bylda_ops_onboarding_completion_operator_handoff,
--   bylda_ops_first_tool_guided_activation
--
-- Endpoints expected by the workflows (REST via PostgREST):
--   GET/POST /rest/v1/ai_operator_configs
--   Filters: user_id=eq.<uuid>
--   Selects: operator_name, operator_tone, primary_niche, recommended_tools,
--            gtm_strategy_summary, brand_voice_keywords, top_3_pain_points

create extension if not exists "pgcrypto";

create table if not exists public.ai_operator_configs (
  id                       uuid primary key default gen_random_uuid(),
  user_id                  uuid not null references auth.users(id) on delete cascade,
  operator_name            text,
  operator_tone            text,
  primary_niche            text,
  recommended_tools        jsonb default '[]'::jsonb,
  gtm_strategy_summary     text,
  brand_voice_keywords     jsonb default '[]'::jsonb,
  top_3_pain_points        jsonb default '[]'::jsonb,
  source_intake_id         uuid,
  llm_model                text default 'claude-3-5-sonnet-20241022',
  llm_prompt_version       text,
  raw_llm_response         jsonb,
  status                   text not null default 'draft' check (status in ('draft','active','archived')),
  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now(),
  unique (user_id)
);

create index if not exists ai_operator_configs_user_id_idx
  on public.ai_operator_configs(user_id);

create index if not exists ai_operator_configs_status_idx
  on public.ai_operator_configs(status);

-- updated_at trigger
create or replace function public.touch_updated_at() returns trigger
language plpgsql as $$
begin new.updated_at := now(); return new; end;
$$;

drop trigger if exists trg_ai_operator_configs_touch on public.ai_operator_configs;
create trigger trg_ai_operator_configs_touch
  before update on public.ai_operator_configs
  for each row execute function public.touch_updated_at();

-- RLS — service role bypasses; deny-by-default for anon/authenticated
alter table public.ai_operator_configs enable row level security;

drop policy if exists "ai_operator_configs_owner_select" on public.ai_operator_configs;
create policy "ai_operator_configs_owner_select"
  on public.ai_operator_configs for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists "ai_operator_configs_owner_modify" on public.ai_operator_configs;
create policy "ai_operator_configs_owner_modify"
  on public.ai_operator_configs for all
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

comment on table public.ai_operator_configs is
  'Per-user AI operator configuration generated by the AI Profile Builder workflow.';
