import { readFileSync } from "node:fs";
import { join } from "node:path";
import { CONTRACTS } from "./index";
import type { Column, Contract, PgType, TableSpec } from "./types";

/**
 * Renders the "Contracts" section of BACKEND_BACKLOG.md from CONTRACTS.
 * Node-only (reads the type files) — never imported by app code.
 * `bun run contracts:doc` writes it; contracts-doc.test.ts fails if it is stale.
 */
export const DOC_START =
  "<!-- CONTRACTS:START — generated by `bun run contracts:doc`, do not edit by hand -->";
export const DOC_END = "<!-- CONTRACTS:END -->";

const DATA_DIR = join(process.cwd(), "src", "lib", "data");

function typeText(file: string, typeName: string): string {
  const base = typeName.split(/[[<]/)[0];
  const src = readFileSync(join(DATA_DIR, file), "utf8");
  const start = src.search(new RegExp(`^export type ${base}\\b`, "m"));
  if (start < 0) return `// see src/lib/data/${file} — ${typeName}`;
  const rest = src.slice(start);
  const firstLine = rest.split("\n")[0];
  if (firstLine.trimEnd().endsWith(";")) return firstLine;
  const end = rest.search(/^};?$/m);
  return rest.slice(0, end + 2).trimEnd();
}

const pg = (t: PgType) => (typeof t === "object" ? `enum(${t.enum.join(" \\| ")})` : t);

function columns(t: TableSpec) {
  const rows = t.columns.map(
    (c: Column) =>
      `| \`${c.name}\` | ${pg(c.type)} | ${c.nullable ? "yes" : ""} | ${[c.fk ? `→ ${c.fk}` : "", c.note ?? ""].filter(Boolean).join(" · ")} |`,
  );
  return [`| Column | Type | Null | Notes |`, `| --- | --- | --- | --- |`, ...rows].join("\n");
}

function section(c: Contract<Record<string, unknown>, unknown>): string {
  const out: string[] = [];
  out.push(`### ${c.id} · ${c.title}`, "");
  out.push(`**Status:** ${c.status} · **Unblocks:** ${c.flows.join(" · ")}`, "");
  out.push(`**Screens:** ${c.screens.map((s) => `\`${s}\``).join(" ")}`, "");
  out.push(`**Closes GAPS.md:** ${c.gaps.join("; ")}`, "");
  out.push(
    `**View model the screens use** — \`${c.viewModel.type}\` (\`src/lib/data/${c.viewModel.file}\`):`,
    "",
    "```ts",
    typeText(c.viewModel.file, c.viewModel.type),
    "```",
    "",
  );
  const tables = c.table ? [c.table, ...(c.extraTables ?? [])] : [];
  for (const t of tables) {
    const kind =
      t.change === "new"
        ? "new table"
        : t.change === "alter"
          ? "alter existing table"
          : "view / RPC result";
    out.push(`**\`${t.name}\`** — ${kind}`, "", columns(t), "", `RLS: ${t.rls}`, "");
    if (t.notes) out.push(`Notes: ${t.notes}`, "");
  }
  out.push(
    "**Endpoints**",
    "",
    "| Kind | Name | Input | Output | Auth |",
    "| --- | --- | --- | --- | --- |",
  );
  for (const e of c.endpoints)
    out.push(`| ${e.kind} | \`${e.name}\` | ${e.input} | ${e.output} | ${e.auth} |`);
  out.push("");
  if (c.example)
    out.push(
      "**Example row** (the contract test validates this against the column spec):",
      "",
      "```json",
      JSON.stringify(c.example, null, 2),
      "```",
      "",
    );
  out.push(
    c.table
      ? `Mapper: \`src/lib/data/${c.domain}/map.ts\` · Contract test: \`src/lib/data/__tests__/contracts/${c.id}.contract.test.ts\``
      : `Derived in \`src/lib/data/${c.domain}/hooks.ts\` · Contract test: \`src/lib/data/__tests__/contracts/${c.id}.contract.test.ts\``,
    "",
  );
  return out.join("\n");
}

export function renderContractsDoc(): string {
  const index = [
    "| # | Contract | Unblocks | Screens | Status |",
    "| --- | --- | --- | --- | --- |",
    ...CONTRACTS.map(
      (c) =>
        `| ${c.id} | [${c.title}](#${c.id.toLowerCase()}) | ${c.flows[0]} | ${c.screens.length} | ${c.status} |`,
    ),
  ].join("\n");
  return [
    DOC_START,
    "",
    `**${CONTRACTS.length} contracts** — every field \`GAPS.md\` marks MISSING, ordered by the screens they unblock (demo Flow 1 · Manager day first). Each one: the view model the screens already use, the proposed table/columns, the endpoint, and a Vitest contract test.`,
    "",
    index,
    "",
    ...CONTRACTS.map((c) => `<a id="${c.id.toLowerCase()}"></a>\n\n${section(c)}`),
    DOC_END,
  ].join("\n");
}

export function spliceDoc(file: string, generated: string): string {
  const s = file.indexOf(DOC_START);
  const e = file.indexOf(DOC_END);
  if (s < 0 || e < 0) return `${file.trimEnd()}\n\n${generated}\n`;
  return file.slice(0, s) + generated + file.slice(e + DOC_END.length);
}
