/**
 * GENERATED from the screen registry (FRAMES.md) by the foundation PR — every V1 view,
 * its Figma node, owning lane, V1 route and screen component. The shell uses it for
 * breadcrumbs; /dev/screens lists it. Edit FRAMES.md + regenerate, never by hand.
 */
export type ScreenKind = "page" | "bare" | "overlay" | "board";
export type ScreenEntry = {
  code: string;
  name: string;
  node: string;
  area: string;
  lane: 1 | 2 | 4 | 5 | 6;
  owner: string;
  /** TanStack route path (with $params), null for overlays/components */
  url: string | null;
  kind: ScreenKind;
  component: string;
};

export const SCREENS: ScreenEntry[] = [
  {
    code: "A1",
    name: "Auth — Sign in",
    node: "26:40",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/sign-in",
    kind: "bare",
    component: "A1AuthSignIn",
  },
  {
    code: "A2",
    name: "Auth — Sign up",
    node: "26:91",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/sign-up",
    kind: "bare",
    component: "A2AuthSignUp",
  },
  {
    code: "A3",
    name: "Auth — Verify email",
    node: "26:139",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/verify",
    kind: "bare",
    component: "A3AuthVerifyEmail",
  },
  {
    code: "A4",
    name: "Auth — Forgot password",
    node: "26:184",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/forgot",
    kind: "bare",
    component: "A4AuthForgotPassword",
  },
  {
    code: "A5",
    name: "Auth — Invite acceptance",
    node: "26:224",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/invite",
    kind: "bare",
    component: "A5AuthInviteAcceptance",
  },
  {
    code: "A6",
    name: "Onboarding — Workspace setup",
    node: "26:784",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/workspace",
    kind: "bare",
    component: "A6OnboardingWorkspaceSetup",
  },
  {
    code: "A7",
    name: "Onboarding — Teach Bylda how you sell",
    node: "15:2",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/teach",
    kind: "bare",
    component: "A7OnboardingTeachByldaHowYouSell",
  },
  {
    code: "A8",
    name: "Onboarding — Connect calls (integration states)",
    node: "15:302",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/connect",
    kind: "bare",
    component: "A8OnboardingConnectCalls",
  },
  {
    code: "A9",
    name: "Onboarding — Invite team",
    node: "26:496",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/invite-team",
    kind: "bare",
    component: "A9OnboardingInviteTeam",
  },
  {
    code: "A10",
    name: "Onboarding — Analysis initializing",
    node: "16:21",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/analysis",
    kind: "bare",
    component: "A10OnboardingAnalysisInitializing",
  },
  {
    code: "A11",
    name: "Onboarding — First insight",
    node: "16:244",
    area: "04",
    lane: 4,
    owner: "Dravin",
    url: "/welcome/first-insight",
    kind: "bare",
    component: "A11OnboardingFirstInsight",
  },
  {
    code: "H1",
    name: "Manager Home — Feed",
    node: "7:2",
    area: "05",
    lane: 1,
    owner: "Ansh",
    url: "/app/home",
    kind: "page",
    component: "H1ManagerHomeFeed",
  },
  {
    code: "H2",
    name: "Manager Home — Team Updates",
    node: "43:692",
    area: "05",
    lane: 1,
    owner: "Ansh",
    url: "/app/home/team-updates",
    kind: "page",
    component: "H2ManagerHomeTeamUpdates",
  },
  {
    code: "H3",
    name: "Manager Home — Calls",
    node: "43:1176",
    area: "05",
    lane: 1,
    owner: "Ansh",
    url: "/app/home/calls",
    kind: "page",
    component: "H3ManagerHomeCalls",
  },
  {
    code: "H4",
    name: "Manager Home — Coaching",
    node: "43:1670",
    area: "05",
    lane: 1,
    owner: "Ansh",
    url: "/app/home/coaching",
    kind: "page",
    component: "H4ManagerHomeCoaching",
  },
  {
    code: "H5",
    name: "Manager Home — Reports",
    node: "43:2139",
    area: "05",
    lane: 1,
    owner: "Ansh",
    url: "/app/home/reports",
    kind: "page",
    component: "H5ManagerHomeReports",
  },
  {
    code: "H6",
    name: "Manager Home — Mentions",
    node: "43:2612",
    area: "05",
    lane: 1,
    owner: "Ansh",
    url: "/app/home/mentions",
    kind: "page",
    component: "H6ManagerHomeMentions",
  },
  {
    code: "H7",
    name: "Admin Home — Owner (workspace health)",
    node: "31:9916",
    area: "05",
    lane: 1,
    owner: "Ansh",
    url: "/app/home/admin",
    kind: "page",
    component: "H7AdminHomeOwner",
  },
  {
    code: "R1",
    name: "Rep Home — Daily Brief",
    node: "8:2",
    area: "06",
    lane: 4,
    owner: "Dravin",
    url: "/app/rep",
    kind: "page",
    component: "R1RepHomeDailyBrief",
  },
  {
    code: "R2",
    name: "Rep — My progress",
    node: "32:129",
    area: "06",
    lane: 4,
    owner: "Dravin",
    url: "/app/rep/progress",
    kind: "page",
    component: "R2RepMyProgress",
  },
  {
    code: "R3",
    name: "Call Review — Rep perspective",
    node: "32:334",
    area: "06",
    lane: 4,
    owner: "Dravin",
    url: "/app/rep/calls/$callId",
    kind: "page",
    component: "R3CallReviewRepPerspective",
  },
  {
    code: "C1",
    name: "Calls Index — saved views",
    node: "17:1090",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls",
    kind: "page",
    component: "C1CallsIndexSavedViews",
  },
  {
    code: "C2",
    name: "Calls Index — All calls + filters open",
    node: "52:8665",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/all",
    kind: "page",
    component: "C2CallsIndexAllCallsFiltersOpen",
  },
  {
    code: "C3",
    name: "Call Review — Transcript & timeline",
    node: "9:2",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/$callId/transcript",
    kind: "page",
    component: "C3CallReviewTranscriptTimeline",
  },
  {
    code: "C4",
    name: "Call Review — Overview",
    node: "44:1375",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/$callId",
    kind: "page",
    component: "C4CallReviewOverview",
  },
  {
    code: "C5",
    name: "Call Review — Analysis",
    node: "44:1755",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/$callId/analysis",
    kind: "page",
    component: "C5CallReviewAnalysis",
  },
  {
    code: "C6",
    name: "Call Review — Coaching",
    node: "44:2146",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/$callId/coaching",
    kind: "page",
    component: "C6CallReviewCoaching",
  },
  {
    code: "C7",
    name: "Calls — Manual upload",
    node: "28:1263",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/upload",
    kind: "page",
    component: "C7CallsManualUpload",
  },
  {
    code: "C8",
    name: "Call comparison",
    node: "28:1464",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/compare",
    kind: "page",
    component: "C8CallComparison",
  },
  {
    code: "C9",
    name: "Calls — Rep view (my calls)",
    node: "28:1646",
    area: "07",
    lane: 2,
    owner: "Mayur",
    url: "/app/calls/mine",
    kind: "page",
    component: "C9CallsRepView",
  },
  {
    code: "I1",
    name: "Intelligence Home",
    node: "27:298",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence",
    kind: "page",
    component: "I1IntelligenceHome",
  },
  {
    code: "I2",
    name: "Behavior Detail — Interrupting during objections",
    node: "11:2",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/behaviors/$behaviorKey",
    kind: "page",
    component: "I2BehaviorDetailInterruptingDuringObjections",
  },
  {
    code: "I3",
    name: "Emerging Patterns",
    node: "27:567",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/patterns",
    kind: "page",
    component: "I3EmergingPatterns",
  },
  {
    code: "I4",
    name: "Objections",
    node: "28:378",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/objections",
    kind: "page",
    component: "I4Objections",
  },
  {
    code: "I5",
    name: "Behavior × Outcome matrix",
    node: "28:641",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/matrix",
    kind: "page",
    component: "I5BehaviorXOutcomeMatrix",
  },
  {
    code: "I6",
    name: "Behavioral Outcome Graph",
    node: "28:857",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/graph",
    kind: "page",
    component: "I6BehavioralOutcomeGraph",
  },
  {
    code: "I7",
    name: "Intelligence — Team behaviors",
    node: "51:1420",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/team-behaviors",
    kind: "page",
    component: "I7IntelligenceTeamBehaviors",
  },
  {
    code: "I8",
    name: "Intelligence — Methodology adherence",
    node: "51:2887",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/methodology",
    kind: "page",
    component: "I8IntelligenceMethodologyAdherence",
  },
  {
    code: "I9",
    name: "Intelligence — Outcome patterns",
    node: "51:1819",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/outcomes",
    kind: "page",
    component: "I9IntelligenceOutcomePatterns",
  },
  {
    code: "I10",
    name: "Intelligence — Rep patterns",
    node: "51:2196",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/reps",
    kind: "page",
    component: "I10IntelligenceRepPatterns",
  },
  {
    code: "I11",
    name: "Intelligence — Prospect patterns",
    node: "51:2556",
    area: "08",
    lane: 1,
    owner: "Ansh",
    url: "/app/intelligence/prospects",
    kind: "page",
    component: "I11IntelligenceProspectPatterns",
  },
  {
    code: "T1",
    name: "Team Overview",
    node: "12:2",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team",
    kind: "page",
    component: "T1TeamOverview",
  },
  {
    code: "T2",
    name: "Team Detail — Mid-Market AE",
    node: "29:1423",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/$teamId",
    kind: "page",
    component: "T2TeamDetailMidMarketAE",
  },
  {
    code: "T3",
    name: "Team Detail — Reps",
    node: "52:2125",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/$teamId/reps",
    kind: "page",
    component: "T3TeamDetailReps",
  },
  {
    code: "T4",
    name: "Team Detail — Behaviors",
    node: "52:2520",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/$teamId/behaviors",
    kind: "page",
    component: "T4TeamDetailBehaviors",
  },
  {
    code: "T5",
    name: "Team Detail — Coaching",
    node: "52:2928",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/$teamId/coaching",
    kind: "page",
    component: "T5TeamDetailCoaching",
  },
  {
    code: "T6",
    name: "Team Detail — Calls",
    node: "52:3276",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/$teamId/calls",
    kind: "page",
    component: "T6TeamDetailCalls",
  },
  {
    code: "T7",
    name: "Team Detail — Settings",
    node: "52:3634",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/$teamId/settings",
    kind: "page",
    component: "T7TeamDetailSettings",
  },
  {
    code: "T8",
    name: "Rep Profile — Jordan Reyes (manager view)",
    node: "12:271",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/reps/$repId",
    kind: "page",
    component: "T8RepProfileJordanReyes",
  },
  {
    code: "T9",
    name: "Rep Profile — Overview",
    node: "45:1147",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/reps/$repId/overview",
    kind: "page",
    component: "T9RepProfileOverview",
  },
  {
    code: "T10",
    name: "Rep Profile — Calls",
    node: "45:1493",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/reps/$repId/calls",
    kind: "page",
    component: "T10RepProfileCalls",
  },
  {
    code: "T11",
    name: "Rep Profile — Coaching",
    node: "45:1841",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/reps/$repId/coaching",
    kind: "page",
    component: "T11RepProfileCoaching",
  },
  {
    code: "T12",
    name: "Rep Profile — Trends",
    node: "45:2142",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/reps/$repId/trends",
    kind: "page",
    component: "T12RepProfileTrends",
  },
  {
    code: "T13",
    name: "Rep Comparison",
    node: "29:1629",
    area: "09",
    lane: 4,
    owner: "Dravin",
    url: "/app/team/compare",
    kind: "page",
    component: "T13RepComparison",
  },
  {
    code: "P1",
    name: "Reports — Index",
    node: "29:159",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/app/reports",
    kind: "page",
    component: "P1ReportsIndex",
  },
  {
    code: "P2",
    name: "Daily Manager Brief — in-app document",
    node: "13:2",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/app/reports/daily",
    kind: "page",
    component: "P2DailyManagerBriefInAppDocument",
  },
  {
    code: "P3",
    name: "Daily Manager Brief — email (640)",
    node: "13:232",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/doc/manager-brief-email",
    kind: "bare",
    component: "P3DailyManagerBriefEmail",
  },
  {
    code: "P4",
    name: "Daily Rep Brief — email / push (60 sec)",
    node: "13:316",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/doc/rep-brief-push",
    kind: "bare",
    component: "P4DailyRepBriefEmailPush",
  },
  {
    code: "P5",
    name: "Weekly Manager Report — living document",
    node: "29:352",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/app/reports/weekly",
    kind: "page",
    component: "P5WeeklyManagerReportLivingDocument",
  },
  {
    code: "P6",
    name: "Weekly Sales Behavior Report — outline",
    node: "52:10624",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/app/reports/outline",
    kind: "page",
    component: "P6WeeklySalesBehaviorReportOutline",
  },
  {
    code: "P7",
    name: "Weekly Rep Report — Jordan",
    node: "29:625",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/app/reports/rep/$repId",
    kind: "page",
    component: "P7WeeklyRepReportJordan",
  },
  {
    code: "P8",
    name: "Team Report — September",
    node: "29:773",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/app/reports/team/$teamId",
    kind: "page",
    component: "P8TeamReportSeptember",
  },
  {
    code: "P9",
    name: "Behavior Report — Objection handling",
    node: "29:993",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/app/reports/behavior/$behaviorKey",
    kind: "page",
    component: "P9BehaviorReportObjectionHandling",
  },
  {
    code: "P10",
    name: "Weekly Report — PDF / print (A4)",
    node: "29:1154",
    area: "10",
    lane: 6,
    owner: "Mayur",
    url: "/doc/weekly-print",
    kind: "bare",
    component: "P10WeeklyReportPDFPrint",
  },
  {
    code: "G1",
    name: "Coaching lifecycle",
    node: "14:2",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: null,
    kind: "overlay",
    component: "G1CoachingLifecycle",
  },
  {
    code: "G2",
    name: "Assign Coaching — modal",
    node: "14:24",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/assign",
    kind: "page",
    component: "G2AssignCoachingModal",
  },
  {
    code: "G3",
    name: "Coaching — Index (Active)",
    node: "30:246",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching",
    kind: "page",
    component: "G3CoachingIndex",
  },
  {
    code: "G4",
    name: "Coaching — Needs follow-up",
    node: "52:6380",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/follow-up",
    kind: "page",
    component: "G4CoachingNeedsFollowUp",
  },
  {
    code: "G5",
    name: "Coaching — Completed",
    node: "30:430",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/completed",
    kind: "page",
    component: "G5CoachingCompleted",
  },
  {
    code: "G6",
    name: "Coaching Detail — Jordan · active",
    node: "30:639",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/$focusId",
    kind: "page",
    component: "G6CoachingDetailJordanActive",
  },
  {
    code: "G7",
    name: "Coaching Detail — Overview",
    node: "46:1604",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/$focusId/overview",
    kind: "page",
    component: "G7CoachingDetailOverview",
  },
  {
    code: "G8",
    name: "Coaching Detail — Evidence",
    node: "46:1935",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/$focusId/evidence",
    kind: "page",
    component: "G8CoachingDetailEvidence",
  },
  {
    code: "G9",
    name: "Coaching Detail — Progress",
    node: "46:2244",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/$focusId/progress",
    kind: "page",
    component: "G9CoachingDetailProgress",
  },
  {
    code: "G10",
    name: "Coaching Detail — Discussion",
    node: "46:2549",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/$focusId/discussion",
    kind: "page",
    component: "G10CoachingDetailDiscussion",
  },
  {
    code: "G11",
    name: "Coaching — Rep view (Jordan)",
    node: "30:839",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/mine",
    kind: "page",
    component: "G11CoachingRepView",
  },
  {
    code: "G12",
    name: "Behavior Change Result — Alex Morgan",
    node: "14:224",
    area: "11",
    lane: 2,
    owner: "Mayur",
    url: "/app/coaching/$focusId/result",
    kind: "page",
    component: "G12BehaviorChangeResultAlexMorgan",
  },
  {
    code: "O1",
    name: "Rooms — Directory",
    node: "31:241",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms",
    kind: "page",
    component: "O1RoomsDirectory",
  },
  {
    code: "O2",
    name: "Room — #objection-watch",
    node: "18:2",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms/$roomId",
    kind: "page",
    component: "O2RoomObjectionWatch",
  },
  {
    code: "O3",
    name: "Room — #objection-watch · Insights",
    node: "48:1283",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms/$roomId/insights",
    kind: "page",
    component: "O3RoomObjectionWatchInsights",
  },
  {
    code: "O4",
    name: "Room — #objection-watch · Calls",
    node: "48:1732",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms/$roomId/calls",
    kind: "page",
    component: "O4RoomObjectionWatchCalls",
  },
  {
    code: "O5",
    name: "Room — #objection-watch · Reports",
    node: "48:2213",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms/$roomId/reports",
    kind: "page",
    component: "O5RoomObjectionWatchReports",
  },
  {
    code: "O6",
    name: "Room — #objection-watch · Files",
    node: "48:2662",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms/$roomId/files",
    kind: "page",
    component: "O6RoomObjectionWatchFiles",
  },
  {
    code: "O7",
    name: "Room — #objection-watch · About",
    node: "48:3103",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms/$roomId/about",
    kind: "page",
    component: "O7RoomObjectionWatchAbout",
  },
  {
    code: "O8",
    name: "Room — #daily-brief",
    node: "31:403",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: null,
    kind: "overlay",
    component: "O8RoomDailyBrief",
  },
  {
    code: "O9",
    name: "Room — #coaching",
    node: "31:586",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: null,
    kind: "overlay",
    component: "O9RoomCoaching",
  },
  {
    code: "O10",
    name: "Room — #mid-market-team (team room)",
    node: "48:25761",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: null,
    kind: "overlay",
    component: "O10RoomMidMarketTeam",
  },
  {
    code: "O11",
    name: "Room — #acme-logistics (deal room)",
    node: "50:3655",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: null,
    kind: "overlay",
    component: "O11RoomAcmeLogistics",
  },
  {
    code: "O12",
    name: "Direct message — Dana ↔ Jordan",
    node: "49:3123",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/dm/$threadId",
    kind: "page",
    component: "O12DirectMessageDanaJordan",
  },
  {
    code: "O13",
    name: "Direct message — BYLDA Coach (rep)",
    node: "49:3627",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/dm/coach",
    kind: "page",
    component: "O13DirectMessageBYLDACoach",
  },
  {
    code: "O14",
    name: "Rooms — New room modal",
    node: "50:4184",
    area: "12",
    lane: 6,
    owner: "Mayur",
    url: "/app/rooms/new",
    kind: "page",
    component: "O14RoomsNewRoomModal",
  },
  {
    code: "S1",
    name: "Search — Command palette ⌘K",
    node: "31:760",
    area: "13",
    lane: 2,
    owner: "Mayur",
    url: null,
    kind: "overlay",
    component: "S1CommandPalette",
  },
  {
    code: "S2",
    name: "Search — Natural-language results",
    node: "31:909",
    area: "13",
    lane: 2,
    owner: "Mayur",
    url: "/app/search",
    kind: "page",
    component: "S2SearchNaturalLanguageResults",
  },
  {
    code: "S3",
    name: "Ask Bylda — side panel (from rail ✦)",
    node: "50:26784",
    area: "13",
    lane: 2,
    owner: "Mayur",
    url: null,
    kind: "overlay",
    component: "S3AskByldaPanel",
  },
  {
    code: "N1",
    name: "Notifications — Drawer over Home",
    node: "31:1101",
    area: "14",
    lane: 1,
    owner: "Ansh",
    url: null,
    kind: "overlay",
    component: "N1NotificationsDrawer",
  },
  {
    code: "N2",
    name: "Notifications — Center",
    node: "31:1258",
    area: "14",
    lane: 1,
    owner: "Ansh",
    url: "/app/notifications",
    kind: "page",
    component: "N2NotificationsCenter",
  },
  {
    code: "X1",
    name: "Integrations — Data sources",
    node: "31:1464",
    area: "15",
    lane: 5,
    owner: "Mayur",
    url: "/app/connections",
    kind: "page",
    component: "X1IntegrationsDataSources",
  },
  {
    code: "X2",
    name: "Integrations — Delivery channels",
    node: "31:1688",
    area: "15",
    lane: 5,
    owner: "Mayur",
    url: "/app/connections/channels",
    kind: "page",
    component: "X2IntegrationsDeliveryChannels",
  },
  {
    code: "X3",
    name: "Integration detail — HubSpot mapping",
    node: "31:1915",
    area: "15",
    lane: 5,
    owner: "Mayur",
    url: "/app/connections/hubspot",
    kind: "page",
    component: "X3IntegrationDetailHubSpotMapping",
  },
  {
    code: "E1",
    name: "Settings — Workspace general",
    node: "31:2201",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace",
    kind: "page",
    component: "E1SettingsWorkspaceGeneral",
  },
  {
    code: "E2",
    name: "Settings — Profile",
    node: "31:2394",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/profile",
    kind: "page",
    component: "E2SettingsProfile",
  },
  {
    code: "E3",
    name: "Settings — Users",
    node: "31:2583",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/users",
    kind: "page",
    component: "E3SettingsUsers",
  },
  {
    code: "E4",
    name: "Settings — Teams",
    node: "31:2828",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/teams",
    kind: "page",
    component: "E4SettingsTeams",
  },
  {
    code: "E5",
    name: "Settings — Roles & permissions",
    node: "31:3018",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/roles",
    kind: "page",
    component: "E5SettingsRolesPermissions",
  },
  {
    code: "E6",
    name: "Settings — Analysis preferences",
    node: "31:3275",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/analysis",
    kind: "page",
    component: "E6SettingsAnalysisPreferences",
  },
  {
    code: "E7",
    name: "Settings — Notifications",
    node: "31:3474",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/notifications",
    kind: "page",
    component: "E7SettingsNotifications",
  },
  {
    code: "E8",
    name: "Settings — Retention & privacy",
    node: "31:3738",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/retention",
    kind: "page",
    component: "E8SettingsRetentionPrivacy",
  },
  {
    code: "E9",
    name: "Methodology — Index",
    node: "31:7762",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/methodology",
    kind: "page",
    component: "E9MethodologyIndex",
  },
  {
    code: "E10",
    name: "Methodology — Detail (stages)",
    node: "31:7973",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/methodology/$methodologyId",
    kind: "page",
    component: "E10MethodologyDetail",
  },
  {
    code: "E11",
    name: "Methodology — Behavior rules list",
    node: "31:8450",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/methodology/$methodologyId/rules",
    kind: "page",
    component: "E11MethodologyBehaviorRulesList",
  },
  {
    code: "E12",
    name: "Methodology — Behavior rule editor",
    node: "31:8218",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/methodology/$methodologyId/rules/$ruleKey",
    kind: "page",
    component: "E12MethodologyBehaviorRuleEditor",
  },
  {
    code: "E13",
    name: "Methodology — Objection library",
    node: "31:8720",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/methodology/objections",
    kind: "page",
    component: "E13MethodologyObjectionLibrary",
  },
  {
    code: "E14",
    name: "Methodology — Success criteria",
    node: "31:8913",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/methodology/success-criteria",
    kind: "page",
    component: "E14MethodologySuccessCriteria",
  },
  {
    code: "E15",
    name: "Settings — Billing & plan",
    node: "31:9113",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/billing",
    kind: "page",
    component: "E15SettingsBillingPlan",
  },
  {
    code: "E16",
    name: "Settings — Usage",
    node: "31:9316",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/usage",
    kind: "page",
    component: "E16SettingsUsage",
  },
  {
    code: "E17",
    name: "Settings — API keys",
    node: "31:9530",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/api-keys",
    kind: "page",
    component: "E17SettingsAPIKeys",
  },
  {
    code: "E18",
    name: "Settings — Audit log",
    node: "31:9715",
    area: "16",
    lane: 5,
    owner: "Mayur",
    url: "/app/workspace/audit-log",
    kind: "page",
    component: "E18SettingsAuditLog",
  },
  {
    code: "Y0",
    name: "Empty & System States — gallery",
    node: "19:2",
    area: "17",
    lane: 5,
    owner: "Mayur",
    url: "/app/states",
    kind: "page",
    component: "Y0EmptySystemStatesGallery",
  },
  {
    code: "B1",
    name: "Mobile — Rep Daily Brief",
    node: "20:2",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/brief",
    kind: "bare",
    component: "B1MobileRepDailyBrief",
  },
  {
    code: "B2",
    name: "Mobile — Manager Brief + alert",
    node: "20:24",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/manager-brief",
    kind: "bare",
    component: "B2MobileManagerBriefAlert",
  },
  {
    code: "B3",
    name: "Mobile — Quick call review + coach",
    node: "20:67",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/calls/$callId",
    kind: "bare",
    component: "B3MobileQuickCallReviewCoach",
  },
  {
    code: "B4",
    name: "Mobile — Coaching acknowledge (Rep)",
    node: "32:572",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/coaching/$focusId",
    kind: "bare",
    component: "B4MobileCoachingAcknowledge",
  },
  {
    code: "B5",
    name: "Mobile — Alerts (Manager)",
    node: "32:605",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/alerts",
    kind: "bare",
    component: "B5MobileAlerts",
  },
  {
    code: "B6",
    name: "Mobile — Moment player (Rep)",
    node: "32:646",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/moments/$momentId",
    kind: "bare",
    component: "B6MobileMomentPlayer",
  },
  {
    code: "B7",
    name: "Mobile — Room #objection-watch",
    node: "52:11424",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/rooms/$roomId",
    kind: "bare",
    component: "B7MobileRoomObjectionWatch",
  },
  {
    code: "B8",
    name: "Mobile — Direct message (Dana ↔ Jordan)",
    node: "52:11495",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/dm/$threadId",
    kind: "bare",
    component: "B8MobileDirectMessage",
  },
  {
    code: "B9",
    name: "Mobile — Ask Bylda / BYLDA Coach",
    node: "52:11547",
    area: "18",
    lane: 5,
    owner: "Mayur",
    url: "/m/ask",
    kind: "bare",
    component: "B9MobileAskByldaBYLDACoach",
  },
];

export const AREA_NAMES: Record<string, string> = {
  "04": "Onboarding",
  "05": "Home",
  "06": "Rep",
  "07": "Calls",
  "08": "Intelligence",
  "09": "Team",
  "10": "Reports",
  "11": "Coaching",
  "12": "Rooms",
  "13": "Search",
  "14": "Notifications",
  "15": "Integrations",
  "16": "Settings",
  "17": "System states",
  "18": "Mobile",
};

/** Match a TanStack fullPath (e.g. "/app/calls/$callId/") to its screen. */
export function screenForRoute(fullPath: string): ScreenEntry | undefined {
  const p = fullPath.length > 1 ? fullPath.replace(/\/$/, "") : fullPath;
  return SCREENS.find((s) => s.url === p);
}
